# Generated by Django 4.1 on 2022-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('ativa', models.BooleanField(default=True)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='CadastroUsuario',
        ),
    ]
