# Generated by Django 4.1 on 2022-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_delete_cadastrousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('raça', models.CharField(max_length=256)),
                ('porte', models.CharField(max_length=256)),
                ('idade', models.IntegerField(max_length=5)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
