# Generated by Django 4.1 on 2022-09-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_petsusuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsusuario',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
