# Generated by Django 4.1 on 2022-09-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_petsusuario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('fone', models.CharField(max_length=256)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.petsusuario')),
            ],
        ),
    ]
