# Generated by Django 4.1 on 2022-09-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('raça', models.CharField(max_length=256)),
                ('porte', models.CharField(max_length=256)),
                ('idade', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('celular', models.CharField(max_length=256)),
                ('idade', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='PetsUsuario',
        ),
        migrations.AddField(
            model_name='pets',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
