# Generated by Django 4.1 on 2022-09-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_usuariologado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='celular',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_completo',
            new_name='porte',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='raça',
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
