# Generated by Django 4.1 on 2022-09-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_rename_celular_usuario_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
