# Generated by Django 4.1 on 2022-09-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_rename_nome_usuario_nome_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
