# Generated by Django 4.1 on 2022-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_rename_nome_completo_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='raça',
            field=models.CharField(max_length=256),
        ),
    ]
