# Generated by Django 4.1 on 2022-09-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0012_alter_usuario_usuariologado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuariologado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
