# Generated by Django 4.1 on 2022-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_alter_usuario_usuariologado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=5)),
                ('banho', models.BooleanField(default=False)),
                ('tosa', models.BooleanField(choices=[('tosacompleta', 'Tosa Completa'), ('tosahigienica', 'Tosa Higiênica'), ('semtosa', 'Sem Tosa')], default=False)),
                ('pulgas', models.BooleanField(default=False)),
                ('observacao', models.CharField(max_length=256)),
            ],
        ),
    ]
