# Generated by Django 4.1 on 2022-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tosa',
            field=models.CharField(choices=[('tosacompleta', 'Tosa Completa'), ('tosahigienica', 'Tosa Higiênica'), ('semtosa', 'Sem Tosa')], max_length=256),
        ),
    ]
