# Generated by Django 4.1 on 2022-11-28 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0019_agendamento_usuariologado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='usuariologado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
