# Generated by Django 4.1 on 2022-11-28 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0020_alter_agendamento_usuariologado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='usuariologado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
