# Generated by Django 4.1 on 2023-02-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_alter_agendamento_usuariologado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
