# Generated by Django 4.1 on 2023-02-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_agendamento_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tosa',
            field=models.CharField(choices=[('Completa', 'Tosa Completa'), ('Higienica', 'Tosa Higiênica'), ('Não', 'Sem Tosa')], max_length=256),
        ),
    ]
