# Generated by Django 4.1 on 2023-02-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_alter_agendamento_tosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='banho',
        ),
    ]
