# Generated by Django 4.1 on 2023-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_remove_agendamento_banho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
