# Generated by Django 4.1 on 2023-02-15 23:32

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0026_alter_agendamento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(validators=[usuario.models.validate_date]),
        ),
    ]
