# Generated by Django 4.1 on 2022-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='apelido',
            field=models.CharField(max_length=256, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='nome',
            field=models.CharField(default=2, max_length=256, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
