# Generated by Django 4.1 on 2022-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_userlogin_nome_completo_userlogin_apelido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='idade',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='data_nascimento',
            field=models.DateField(default=None, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
