# Generated by Django 4.1 on 2022-09-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_userlogin_idade_userlogin_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='data_nascimento',
        ),
    ]
