# Generated by Django 4.1 on 2022-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_remove_userlogin_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
