# Generated by Django 4.1 on 2022-09-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_userlogin_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='data_nascimento',
            new_name='datanascimento',
        ),
    ]
