# Generated by Django 4.1 on 2022-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_rename_data_nascimento_userlogin_datanascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='datanascimento',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='data_nascimento',
            field=models.CharField(max_length=123, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
