# Generated by Django 4.1 on 2022-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_userlogin_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
