# Generated by Django 4.1 on 2023-03-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospagamentos',
            name='Plano',
        ),
        migrations.AddField(
            model_name='dadospagamentos',
            name='Planos',
            field=models.BooleanField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default=False, max_length=256),
            preserve_default=False,
        ),
    ]
