# Generated by Django 4.1 on 2023-03-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_alter_dadospagamentos_banhos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospagamentos',
            name='Planos',
            field=models.BooleanField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=256),
        ),
    ]
